export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const SET_IS_FETCHING_AUTH_USER = "SET_IS_FETCHING_AUTH_USER";
export const RESET_AUTH = "RESET_AUTH";

